"""stock out add column

Revision ID: 55762d67a0b2
Revises: 
Create Date: 2023-01-04 16:33:22.335791

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '55762d67a0b2'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biz_stock_out', sa.Column('summary', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biz_stock_out', 'summary')
    # ### end Alembic commands ###
