"""apply item add columns

Revision ID: a7122ce974a0
Revises: 
Create Date: 2023-11-29 15:51:09.992169

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a7122ce974a0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biz_asset_item', sa.Column('is_bought', sa.Boolean(), nullable=True))
    op.add_column('biz_asset_item', sa.Column('is_stored', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biz_asset_item', 'is_stored')
    op.drop_column('biz_asset_item', 'is_bought')
    # ### end Alembic commands ###
