"""change column name

Revision ID: a82ea98974b8
Revises: e8ecb22a54a2
Create Date: 2023-11-30 15:32:04.333695

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82ea98974b8'
down_revision = 'e8ecb22a54a2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biz_asset_item', sa.Column('tmp', sa.String(length=32), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('biz_asset_item', 'tmp')
    # ### end Alembic commands ###
