"""change column name

Revision ID: e8ecb22a54a2
Revises: a7122ce974a0
Create Date: 2023-11-30 15:27:51.087422

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e8ecb22a54a2'
down_revision = 'a7122ce974a0'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biz_asset_item', sa.Column('std_model_id', sa.String(length=32), nullable=True))
    op.drop_column('biz_asset_item', 'std_model')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('biz_asset_item', sa.Column('std_model', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('biz_asset_item', 'std_model_id')
    # ### end Alembic commands ###
